name: change_color
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ../../flare_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
