name: teddy
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flare_flutter:
    path: ../../flare_flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
  assets:
    - assets/