name: favorite
description: A tappable Flare Widget.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter:
    path: ../../flare_flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Light.ttf
  assets:
    - assets/
